@host = http://localhost:3000

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGl0ZXNvLm14IiwiaWF0IjoxNjE5NzM2NjQzLCJleHAiOjE2MTk3NDAyNDN9.awRdGwu9jayaqHmmwIHooiOhpwPNeaKpsuvtQhAYARU


###
POST {{host}}/login_route
Content-Type: application/json 
{
    "email": "test1@iteso.mx",
    "password": "123"
}

###
GET {{host}}/user_route
x-auth: {{token}}